export const styles = (dark) => ({
  app: {
    minHeight: "100vh",
    background: dark ? "#0a0a0a" : "#f5f5f0",
    color: dark ? "#f0ede8" : "#1a1a1a",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    transition: "all 0.3s ease",
  },
  header: {
    background: dark ? "#111111" : "#ffffff",
    borderBottom: "3px solid #f97316",
    padding: "0",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: dark ? "0 4px 20px rgba(249,115,22,0.15)" : "0 4px 20px rgba(0,0,0,0.08)",
  },
  headerInner: {
    maxWidth: 1200,
    margin: "0 auto",
    padding: "18px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  logo: { display: "flex", flexDirection: "column", gap: 2 },
  logoTop: {
    fontSize: 11,
    fontFamily: "'Arial Narrow', Arial, sans-serif",
    letterSpacing: "0.25em",
    textTransform: "uppercase",
    color: "#f97316",
    fontWeight: 700,
  },
  logoTitle: {
    fontSize: 26,
    fontWeight: 900,
    letterSpacing: "-0.03em",
    color: dark ? "#ffffff" : "#0a0a0a",
    lineHeight: 1,
  },
  logoBadge: {
    display: "inline-block",
    background: "#f97316",
    color: "#fff",
    fontSize: 10,
    fontFamily: "Arial, sans-serif",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    padding: "2px 8px",
    borderRadius: 2,
    marginTop: 4,
    fontWeight: 700,
  },
  toggleBtn: {
    background: dark ? "#1f1f1f" : "#f0ede8",
    border: `2px solid ${dark ? "#333" : "#ddd"}`,
    color: dark ? "#f0ede8" : "#1a1a1a",
    borderRadius: 50,
    width: 52,
    height: 28,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: dark ? "flex-end" : "flex-start",
    padding: "0 4px",
    transition: "all 0.3s",
  },
  toggleKnob: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    background: "#f97316",
    transition: "all 0.3s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
  },
  nav: {
    background: dark ? "#161616" : "#fafaf8",
    borderBottom: `1px solid ${dark ? "#2a2a2a" : "#e8e8e0"}`,
    overflowX: "auto",
  },
  navInner: {
    maxWidth: 1200,
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    gap: 0,
  },
  navBtn: (active) => ({
    background: "none",
    border: "none",
    borderBottom: active ? "3px solid #f97316" : "3px solid transparent",
    color: active ? "#f97316" : dark ? "#888" : "#555",
    padding: "14px 18px",
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "Arial, sans-serif",
    fontWeight: active ? 700 : 400,
    letterSpacing: "0.05em",
    whiteSpace: "nowrap",
    transition: "all 0.2s",
    textTransform: "uppercase",
  }),
  main: { maxWidth: 1200, margin: "0 auto", padding: "40px 24px" },
  sectionTitle: {
    fontSize: 28,
    fontWeight: 900,
    letterSpacing: "-0.02em",
    marginBottom: 6,
    color: dark ? "#ffffff" : "#0a0a0a",
  },
  sectionSub: {
    fontSize: 14,
    color: dark ? "#666" : "#999",
    fontFamily: "Arial, sans-serif",
    marginBottom: 32,
    letterSpacing: "0.02em",
  },
  booksGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 28,
  },
  bookCard: {
    background: dark ? "#141414" : "#ffffff",
    border: `1px solid ${dark ? "#222" : "#e8e8e0"}`,
    borderRadius: 4,
    overflow: "hidden",
    transition: "all 0.25s",
    cursor: "pointer",
    position: "relative",
  },
  bookRank: {
    position: "absolute",
    top: 10,
    left: 10,
    background: "#f97316",
    color: "#fff",
    width: 28,
    height: 28,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 900,
    fontFamily: "Arial, sans-serif",
    zIndex: 2,
  },
  bookImg: {
    width: "100%",
    aspectRatio: "2/3",
    objectFit: "cover",
    display: "block",
    background: dark ? "#1f1f1f" : "#f0ede8",
  },
  bookBody: { padding: "14px" },
  bookTitle: {
    fontSize: 14,
    fontWeight: 700,
    lineHeight: 1.3,
    marginBottom: 4,
    color: dark ? "#f0ede8" : "#1a1a1a",
  },
  bookAuthor: {
    fontSize: 12,
    color: "#f97316",
    fontFamily: "Arial, sans-serif",
    marginBottom: 8,
    letterSpacing: "0.03em",
  },
  bookWeeks: {
    fontSize: 11,
    color: dark ? "#555" : "#aaa",
    fontFamily: "Arial, sans-serif",
  },
  bookDesc: {
    fontSize: 12,
    color: dark ? "#888" : "#666",
    lineHeight: 1.5,
    marginTop: 6,
    fontStyle: "italic",
  },
  inputRow: { display: "flex", gap: 12, marginBottom: 32, flexWrap: "wrap" },
  input: {
    flex: 1,
    minWidth: 220,
    background: dark ? "#141414" : "#ffffff",
    border: `2px solid ${dark ? "#2a2a2a" : "#e0ddd8"}`,
    borderRadius: 4,
    color: dark ? "#f0ede8" : "#1a1a1a",
    fontSize: 15,
    padding: "12px 16px",
    fontFamily: "Georgia, serif",
    outline: "none",
    transition: "border-color 0.2s",
  },
  btn: {
    background: "#f97316",
    border: "none",
    color: "#fff",
    padding: "12px 28px",
    borderRadius: 4,
    fontSize: 14,
    fontFamily: "Arial, sans-serif",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    cursor: "pointer",
    transition: "background 0.2s",
  },
  loading: {
    textAlign: "center",
    padding: "60px 0",
    color: "#f97316",
    fontSize: 16,
    fontFamily: "Arial, sans-serif",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
  },
  error: {
    background: dark ? "#1a0a00" : "#fff3e0",
    border: "2px solid #f97316",
    borderRadius: 4,
    padding: "16px 20px",
    color: "#f97316",
    fontFamily: "Arial, sans-serif",
    fontSize: 14,
  },
  listRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "14px 0",
    borderBottom: `1px solid ${dark ? "#1f1f1f" : "#f0ede8"}`,
  },
  tag: {
    background: dark ? "#1f1f1f" : "#f0ede8",
    border: `1px solid ${dark ? "#2a2a2a" : "#e0ddd8"}`,
    borderRadius: 2,
    padding: "4px 10px",
    fontSize: 11,
    fontFamily: "Arial, sans-serif",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: dark ? "#888" : "#666",
  },
  reviewCard: {
    background: dark ? "#141414" : "#ffffff",
    border: `1px solid ${dark ? "#222" : "#e8e8e0"}`,
    borderLeft: "4px solid #f97316",
    borderRadius: 4,
    padding: "20px 24px",
    marginBottom: 16,
  },
  historyItem: {
    background: dark ? "#141414" : "#ffffff",
    border: `1px solid ${dark ? "#222" : "#e8e8e0"}`,
    borderRadius: 4,
    padding: "16px 20px",
    marginBottom: 12,
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
  },
  weeksBar: {
    height: 6,
    background: "#f97316",
    borderRadius: 3,
    marginTop: 6,
    transition: "width 0.5s",
  },
  overviewSection: { marginBottom: 40 },
  divider: {
    border: "none",
    borderTop: `1px solid ${dark ? "#2a2a2a" : "#e8e8e0"}`,
    margin: "32px 0",
  },
});